import type { AirBases } from "@ipc-bindings/map_info";

export const air_bases: AirBases = {
  bases: {
    "393217": {
      rid: 1,
      action_kind: 1,
      area_id: 6,
      name: "第一基地航空隊",
      distance: 7,
      plane_info: [
        {
          cond: 0,
          state: 1,
          max_count: 4,
          count: 2,
          slotid: 2716,
          squadron_id: 1,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 0,
          slotid: 21523,
          squadron_id: 2,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 10,
          slotid: 22185,
          squadron_id: 3,
        },
        {
          cond: 0,
          state: 1,
          max_count: 9,
          count: 6,
          slotid: 11163,
          squadron_id: 4,
        },
      ],
    },
    "393218": {
      rid: 2,
      action_kind: 1,
      area_id: 6,
      name: "第二基地航空隊",
      distance: 7,
      plane_info: [
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 13,
          slotid: 9575,
          squadron_id: 1,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 11,
          slotid: 13381,
          squadron_id: 2,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 13,
          slotid: 13420,
          squadron_id: 3,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 12,
          slotid: 16572,
          squadron_id: 4,
        },
      ],
    },
    "393219": {
      rid: 3,
      action_kind: 2,
      area_id: 6,
      name: "第三基地航空隊",
      distance: 1,
      plane_info: [
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 14,
          slotid: 5733,
          squadron_id: 1,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 14,
          slotid: 5734,
          squadron_id: 2,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 15,
          slotid: 9688,
          squadron_id: 3,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 16,
          slotid: 14277,
          squadron_id: 4,
        },
      ],
    },
    "458753": {
      rid: 1,
      action_kind: 1,
      area_id: 7,
      name: "第一基地航空隊",
      distance: 2,
      plane_info: [
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 15,
          slotid: 21522,
          squadron_id: 1,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 16,
          slotid: 11952,
          squadron_id: 2,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 13,
          slotid: 9463,
          squadron_id: 3,
        },
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 13,
          slotid: 1273,
          squadron_id: 4,
        },
      ],
    },
    "458754": {
      rid: 2,
      action_kind: 1,
      area_id: 7,
      name: "第二基地航空隊",
      distance: 4,
      plane_info: [
        {
          cond: 0,
          state: 1,
          max_count: 18,
          count: 18,
          slotid: 25578,
          squadron_id: 1,
        },
        {
          cond: null,
          state: 0,
          max_count: null,
          count: null,
          slotid: 0,
          squadron_id: 2,
        },
        {
          cond: null,
          state: 0,
          max_count: null,
          count: null,
          slotid: 0,
          squadron_id: 3,
        },
        {
          cond: null,
          state: 0,
          max_count: null,
          count: null,
          slotid: 0,
          squadron_id: 4,
        },
      ],
    },
  },
};
