import type { Cells } from "@ipc-bindings/cells";

export const cells: Cells = {
  maparea_id: 1,
  mapinfo_no: 1,
  bosscell_no: 3,
  bosscomp: 1,
  cells: {
    "1": {
      timestamp: 1755412652,
      rashin_id: 0,
      no: 1,
      color_no: 4,
      event_id: 4,
      event_kind: 1,
      next: 1,
      e_deck_info: [
        {
          kind: 0,
          ship_ids: [1503],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
    "3": {
      timestamp: 1755412717,
      rashin_id: 2,
      no: 3,
      color_no: 5,
      event_id: 5,
      event_kind: 1,
      next: 0,
      e_deck_info: [
        {
          kind: 0,
          ship_ids: [1505, 1502, 1502],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
  },
  cell_index: [1, 3],
  cell_data: [
    {
      id: 3001,
      no: 0,
      color_no: 0,
      passed: 0,
      distance: null,
    },
    {
      id: 3002,
      no: 1,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3003,
      no: 2,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3004,
      no: 3,
      color_no: 5,
      passed: 1,
      distance: null,
    },
  ],
  battles: {
    "1": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 1,
        },
        {
          Hougeki: 2,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1755412663,
      midnight_timestamp: null,
      cell_id: 1,
      deck_id: 1,
      formation: [1, 1, 1],
      enemy_ship_id: [1503],
      e_params: [[6, 16, 6, 7]],
      e_slot: [[1502, 1513, -1, -1, -1]],
      e_hp_max: [24],
      f_total_damages: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [5, 5],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: null,
      opening_raigeki: {
        fdam: [0, 0, 0, 0, 0, 0, 0],
        edam: [102, 0, 0, 0, 0, 0, 0],
        frai_list_items: [[0], null, null, null, null, null, null],
        erai_list_items: [null, null, null, null, null, null, null],
        fcl_list: [1, 1, 1, 1, 1, 1, 1],
        ecl_list: [2, 1, 1, 1, 1, 1, 1],
        f_protect_flag: [false, false, false, false, false, false, false],
        e_protect_flag: [false, false, false, false, false, false, false],
        f_now_hps: [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        e_now_hps: [24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      hougeki: null,
      closing_raigeki: null,
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [42, 15],
      e_nowhps: [24],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
    "3": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 1,
        },
        {
          Hougeki: 2,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1755412730,
      midnight_timestamp: null,
      cell_id: 3,
      deck_id: 1,
      formation: [1, 1, 2],
      enemy_ship_id: [1505, 1502, 1502],
      e_params: [
        [14, 24, 10, 15],
        [7, 16, 7, 6],
        [7, 16, 7, 6],
      ],
      e_slot: [
        [1504, 1525, -1, -1, -1],
        [1502, -1, -1, -1, -1],
        [1502, -1, -1, -1, -1],
      ],
      e_hp_max: [33, 22, 22],
      f_total_damages: [4, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [92, 83, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [5, 1],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [33, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: null,
      opening_raigeki: {
        fdam: [0, 0, 0, 0, 0, 0, 0],
        edam: [0, 83, 0, 0, 0, 0, 0],
        frai_list_items: [[1], null, null, null, null, null, null],
        erai_list_items: [null, null, null, null, null, null, null],
        fcl_list: [1, 1, 1, 1, 1, 1, 1],
        ecl_list: [1, 2, 1, 1, 1, 1, 1],
        f_protect_flag: [false, false, false, false, false, false, false],
        e_protect_flag: [false, false, false, false, false, false, false],
        f_now_hps: [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        e_now_hps: [33, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      hougeki: [
        {
          at_list: [0, 1, 2],
          at_type: [0, 0, 0],
          df_list: [[0], [2], [0]],
          cl_list: [[2], [1], [1]],
          damage: [[92], [8], [4]],
          at_eflag: [0, 0, 1],
          si_list: [[310], [297], [1502]],
          protect_flag: [[false], [false], [false]],
          f_now_hps: [
            [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [42, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          ],
          e_now_hps: [
            [33, -61, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [-59, -61, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [-59, -61, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          ],
        },
        null,
        null,
      ],
      closing_raigeki: {
        fdam: [0, 11, 0, 0, 0, 0, 0],
        edam: [0, 0, 103, 0, 0, 0, 0],
        frai: [2, 2, -1, -1, -1, -1, -1],
        erai: [-1, -1, 1, -1, -1, -1, -1],
        fcl: [1, 1, 1, 1, 1, 1, 1],
        ecl: [1, 1, 2, 1, 1, 1, 1],
        f_protect_flag: [false, false, false, false, false, false, false],
        e_protect_flag: [false, false, false, false, false, false, false],
        f_now_hps: [38, 15, 0, 0, 0, 0, 0],
        e_now_hps: [-59, -61, 14, 0, 0, 0, 0],
      },
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [42, 15],
      e_nowhps: [33, 22, 22],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
  },
  event_map: null,
};
