import type { Cells } from "@ipc-bindings/cells";

export const cells_1_5: Cells = {
  maparea_id: 1,
  mapinfo_no: 5,
  bosscell_no: 10,
  bosscomp: 1,
  cells: {
    "1": {
      timestamp: 1758549885,
      rashin_id: 0,
      no: 1,
      color_no: 4,
      event_id: 4,
      event_kind: 1,
      next: 1,
      e_deck_info: [
        {
          kind: 0,
          ship_ids: [1532, 1530],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
    "4": {
      timestamp: 1758549942,
      rashin_id: 0,
      no: 4,
      color_no: 4,
      event_id: 4,
      event_kind: 1,
      next: 1,
      e_deck_info: [
        {
          kind: 0,
          ship_ids: [1533, 1531, 1531],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
    "5": {
      timestamp: 1758549997,
      rashin_id: 4,
      no: 5,
      color_no: 4,
      event_id: 4,
      event_kind: 1,
      next: 1,
      e_deck_info: [
        {
          kind: 0,
          ship_ids: [1532, 1532, 1530],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
    "11": {
      timestamp: 1758550060,
      rashin_id: 2,
      no: 11,
      color_no: 5,
      event_id: 5,
      event_kind: 1,
      next: 0,
      e_deck_info: [
        {
          kind: 1,
          ship_ids: [1535, 1530, 1530],
        },
      ],
      limit_state: 0,
      m1: null,
      destruction_battle: null,
      happening: null,
    },
  },
  cell_index: [1, 4, 5, 11],
  cell_data: [
    {
      id: 3092,
      no: 0,
      color_no: 0,
      passed: 0,
      distance: null,
    },
    {
      id: 3093,
      no: 1,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3094,
      no: 2,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3095,
      no: 3,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3096,
      no: 4,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3097,
      no: 5,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3098,
      no: 6,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3099,
      no: 7,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3100,
      no: 8,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3101,
      no: 9,
      color_no: 4,
      passed: 1,
      distance: null,
    },
    {
      id: 3102,
      no: 10,
      color_no: 5,
      passed: 1,
      distance: null,
    },
    {
      id: 3103,
      no: 11,
      color_no: 5,
      passed: 1,
      distance: null,
    },
    {
      id: 3104,
      no: 12,
      color_no: 5,
      passed: 1,
      distance: null,
    },
  ],
  battles: {
    "1": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 0,
        },
        {
          Hougeki: 1,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1758549902,
      midnight_timestamp: null,
      cell_id: 1,
      deck_id: 1,
      formation: [5, 4, 3],
      enemy_ship_id: [1532, 1530],
      e_params: [
        [0, 64, 0, 21],
        [0, 42, 0, 7],
      ],
      e_slot: [
        [1515, 1513, 1513, -1, -1],
        [1513, 1513, -1, -1, -1],
      ],
      e_hp_max: [27, 19],
      f_total_damages: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [108, 117, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [6, 5],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [27, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: {
        at_list: [0, 3],
        at_type: [0, 0],
        df_list: [[1], [0]],
        cl_list: [[2], [2]],
        damage: [[117], [108]],
        at_eflag: [0, 0],
        si_list: [[45], [45]],
        protect_flag: [[false], [false]],
        f_now_hps: [
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        e_now_hps: [
          [27, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [27, -98, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
      },
      opening_raigeki: null,
      hougeki: null,
      closing_raigeki: null,
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [17, 17, 17, 17],
      e_nowhps: [27, 19],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
    "4": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 0,
        },
        {
          Hougeki: 1,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1758549954,
      midnight_timestamp: null,
      cell_id: 4,
      deck_id: 1,
      formation: [5, 4, 2],
      enemy_ship_id: [1533, 1531, 1531],
      e_params: [
        [0, 74, 0, 27],
        [0, 52, 0, 9],
        [0, 52, 0, 9],
      ],
      e_slot: [
        [1515, 1514, 1514, -1, -1],
        [1514, 1514, -1, -1, -1],
        [1514, 1514, -1, -1, -1],
      ],
      e_hp_max: [34, 24, 24],
      f_total_damages: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [61, 73, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [6, 5],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [34, 24, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: {
        at_list: [0, 1, 2],
        at_type: [0, 0, 0],
        df_list: [[2], [0], [1]],
        cl_list: [[2], [2], [2]],
        damage: [[114], [61], [73]],
        at_eflag: [0, 0, 0],
        si_list: [[45], [45], [45]],
        protect_flag: [[false], [false], [false]],
        f_now_hps: [
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        e_now_hps: [
          [34, 24, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [34, 24, -90, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [-27, 24, -90, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
      },
      opening_raigeki: null,
      hougeki: null,
      closing_raigeki: null,
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [17, 17, 17, 17],
      e_nowhps: [34, 24, 24],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
    "5": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 0,
        },
        {
          Hougeki: 1,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1758550013,
      midnight_timestamp: null,
      cell_id: 5,
      deck_id: 1,
      formation: [5, 4, 3],
      enemy_ship_id: [1532, 1532, 1530],
      e_params: [
        [0, 64, 0, 21],
        [0, 64, 0, 21],
        [0, 42, 0, 7],
      ],
      e_slot: [
        [1515, 1513, 1513, -1, -1],
        [1515, 1513, 1513, -1, -1],
        [1513, 1513, -1, -1, -1],
      ],
      e_hp_max: [27, 27, 19],
      f_total_damages: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [97, 109, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [5, 5],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [27, 27, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: {
        at_list: [3, 2, 1],
        at_type: [0, 0, 0],
        df_list: [[0], [1], [2]],
        cl_list: [[2], [2], [2]],
        damage: [[97], [109], [115]],
        at_eflag: [0, 0, 0],
        si_list: [[45], [45], [45]],
        protect_flag: [[false], [false], [false]],
        f_now_hps: [
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        e_now_hps: [
          [27, 27, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [-70, 27, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [-70, -82, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
      },
      opening_raigeki: null,
      hougeki: null,
      closing_raigeki: null,
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [17, 17, 17, 17],
      e_nowhps: [27, 27, 19],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
    "11": {
      battle_order: [
        {
          AirBaseAssult: null,
        },
        {
          CarrierBaseAssault: null,
        },
        {
          AirBaseAirAttack: null,
        },
        {
          OpeningAirAttack: 0,
        },
        {
          SupportAttack: null,
        },
        {
          OpeningTaisen: null,
        },
        {
          OpeningRaigeki: null,
        },
        {
          Hougeki: 0,
        },
        {
          Hougeki: 1,
        },
        {
          ClosingRaigeki: null,
        },
      ],
      timestamp: 1758550076,
      midnight_timestamp: null,
      cell_id: 11,
      deck_id: 1,
      formation: [5, 4, 1],
      enemy_ship_id: [1535, 1530, 1530, 1530],
      e_params: [
        [0, 96, 0, 36],
        [0, 42, 0, 7],
        [0, 42, 0, 7],
        [0, 42, 0, 7],
      ],
      e_slot: [
        [1515, 1515, 1514, -1, -1],
        [1513, 1513, -1, -1, -1],
        [1513, 1513, -1, -1, -1],
        [1513, 1513, -1, -1, -1],
      ],
      e_hp_max: [44, 19, 19, 19],
      f_total_damages: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      e_total_damages: [69, 97, 152, 97, 0, 0, 0, 0, 0, 0, 0, 0],
      friend_total_damages: null,
      midnight_f_total_damages: null,
      midnight_e_total_damages: null,
      reconnaissance: [6, 5],
      escape_idx: null,
      smoke_type: 0,
      combat_ration: null,
      balloon_flag: 0,
      air_base_assault: null,
      carrier_base_assault: null,
      air_base_air_attacks: null,
      opening_air_attack: [
        {
          air_superiority: 1,
          air_fire: null,
          f_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          e_damage: {
            plane_from: null,
            touch_plane: -1,
            loss_plane1: 0,
            loss_plane2: 0,
            damages: null,
            cl: null,
            sp: null,
            rai_flag: null,
            bak_flag: null,
            protect_flag: null,
            now_hps: [44, 19, 19, 19, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        },
        null,
      ],
      support_attack: null,
      opening_taisen: {
        at_list: [2, 3, 1, 0],
        at_type: [0, 0, 0, 0],
        df_list: [[2], [1], [3], [0]],
        cl_list: [[2], [2], [2], [2]],
        damage: [[152], [97], [97], [69]],
        at_eflag: [0, 0, 0, 0],
        si_list: [[45], [45], [45], [45]],
        protect_flag: [[false], [true], [true], [false]],
        f_now_hps: [
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
          [17, 17, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        e_now_hps: [
          [44, 19, 19, 19, 0, 0, 0, 0, 0, 0, 0, 0],
          [44, 19, -133, 19, 0, 0, 0, 0, 0, 0, 0, 0],
          [44, -78, -133, 19, 0, 0, 0, 0, 0, 0, 0, 0],
          [44, -78, -133, -78, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
      },
      opening_raigeki: null,
      hougeki: null,
      closing_raigeki: null,
      friendly_force_attack: null,
      midnight_flare_pos: null,
      midnight_touchplane: null,
      midnight_hougeki: null,
      f_nowhps: [17, 17, 17, 17],
      e_nowhps: [44, 19, 19, 19],
      midnight_f_nowhps: null,
      midnight_e_nowhps: null,
    },
  },
  event_map: null,
};
